### ISSUE TITLE
Add a search feature

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#115]
I would like to have a search feature. 
How complicated is that in Rails?

**Comment by sareg0** [comment]
do we close issues like this that are a bit 'inactive' / not going to be implemented yet?

**Comment by til** [comment]
I'd say yes. Close it ...

**Comment by PragTob** [comment]
Hm, I dunno - I like to keep them around, maybe with a special tag/milestone as to when we look at things and are like "oh we could do that" or someone sees that there is already an issue for that.

That said, my repos then often tend to have a lot of open issues :(
