### ISSUE TITLE
Sending email from rails to google groups fails

### ISSUE THREAD

**Issue by til** [rubycorns/rorganize.it#162]
When we tested #155 yesterday on shellycloud, we entered the google groups mail address rails-girls-berlin-project-group-tuesdays@googlegroups.com as the address of the rubycorns group, left and joined a group. According to the log, an email was sent, but it never arrived on the groups list. Afterwards we changed the address to a private one of Tam, left and joined a group, and that email then arrived.

Google groups propably thinks the email is not legitimate and drops it. Before bashing google too much, this might be even the correct behaviour because people not on the list can not send mail to it.

What can we do about this to avoid other groups running into this problem and missing important join emails?

I have two ideas:
- add a note below the group email field that it needs to accept mail from whatever our default sender address is, and a closed mailing list won't work
- send the emails to every member of the group individually. This would make the group mail address obsolete again. We'd need to be careful to not expose email addresses of members to other members when adding this, ie. not send one email to many people in To:, but rather many individual mails etc.

**Comment by sareg0** [comment]
I am a fan of the first option. It's low cost for now. Imma adopt this issue and add that.

**Comment by sareg0** [comment]
oh actually! @til we already have this as a direction on the contact email field... So I this issue can now be close?

**Comment by til** [comment]
I agree! Please, close this, it's over three years old! *gasp* 😄

**Comment by sareg0** [comment]
woot!! \o/
