### ISSUE TITLE
Cleanup group model relationships?!?!

### ISSUE THREAD

**Issue by PragTob** [rubycorns/rorganize.it#202]
I'm not sure we really need all the relationships we have in our model right now...

```ruby
  has_many :students, through: :student_memberships, source: :person
  has_many :coaches, through: :coach_memberships, source: :person
  has_many :topics
  has_many :people, through: :memberships
  has_many :memberships, dependent: :destroy
  has_many :student_memberships
  has_many :coach_memberships
```

Looks to me like either the standard people/memberships could go or the specialized ones... or the rellationships can go and we just specify the join table? I don't know.
@til ?

**Comment by lislis** [comment]
I actually think we need all of them

**Comment by lislis** [comment]
So, I'm closing this. Re-open if you think otherwise.
