### ISSUE TITLE
logoooooo

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#234]
our logo sucks. 
we need a new one.

**Comment by sareg0** [comment]
I like this pixel art idea

![screen shot 2015-01-07 at 12 07 44 pm](https://cloud.githubusercontent.com/assets/1307818/5644647/3cbc0236-9666-11e4-9f0d-13b7682ab803.png)

**Comment by sareg0** [comment]
http://media.tumblr.com/tumblr_lt48qy6sIC1qmvaoo.gif

**Comment by BriocheBerlin** [comment]
Slightly disturbing!

**Comment by sareg0** [comment]
![img_2911](https://cloud.githubusercontent.com/assets/1307818/5978104/9820d018-a89d-11e4-9351-334d85b52fd5.JPG)

**Comment by sareg0** [comment]
![rubycorn1](https://cloud.githubusercontent.com/assets/1307818/5978188/4cbf6a0c-a89e-11e4-81b6-2e959d6fbbc9.png)

**Comment by sareg0** [comment]
Oh here is the Rails Girls Munich logo

![img_2912](https://cloud.githubusercontent.com/assets/1307818/5978656/b1fa7e54-a8a1-11e4-9034-5fd0a247d8e2.JPG)

**Comment by berlintam** [comment]
I love it! However, it makes me a little bit nervous to see how that girl is carrying her computer....

**Comment by sareg0** [comment]
totally... but she has learned since ;)

**Comment by sareg0** [comment]
https://www.youtube.com/watch?v=qRC4Vk6kisY
What about pink fluffy unicorns dancing on rainbows?

**Comment by Malwine** [comment]
Since the app is renamed: do we still want a logo? for us? for the app?

**Comment by sareg0** [comment]
I guess we still want to have a logo for our group, but one for the app seems more important at this point. I think @lislis is fashioning a little unicorn from ASCII that moves. Did you have anything in mind @malwine?

**Comment by til** [comment]
I'm very much in favor of a logo for the app, and second the question:
did you have anything in mind, Malwine?

**Comment by Malwine** [comment]
No, I was just wondering. 
And also a logo for "rorganize it" is a tough one :smile:

**Comment by sareg0** [comment]
totally... I was thinking a roaring lion :D but have not followed through on that idea yet.

**Comment by sareg0** [comment]
I am gonna close this issue up, since we have the logo now... and stickers :)
