### ISSUE TITLE
New Title for App

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#283]
Currently the title of the App is still 'RailsGirlsApp' in the top left of the page.

What is the app called? We have not yet solved the issue of the domain, but we could still give it a more descriptive name, so people who stumble across it know what it is :)

My suggestion, based on a brief discussion with Tam

'Project Gruppe Finderinnen'
heheeheh... Discuss.

**Comment by sareg0** [comment]
holy crap... the seratonin levels in my brain went through the roof when I saw that thing!

**Comment by BriocheBerlin** [comment]
I think this is closed now.
