### ISSUE TITLE
non-public/public profile

### ISSUE THREAD

**Issue by 1000miles** [rubycorns/rorganize.it#284]
dear rubycorns, 

for privacy reasons i would love to suggest following feature:
- provide a button for every user to switch from "visible" (in public listing) to "hidden" (only visible for logged-in users)

what do you think?

best,
thuy

**Comment by berlintam** [comment]
hey, what's the status on this? @1000miles did you still want to take a look at it?

**Comment by 1000miles** [comment]
@berlintam I am sorry, I seem to have missed your comment from 12 days ago. 
What do you mean by taking a look at it? As far as I can see the profile names are still public to everyone, so this task is still in backlog, or? Waffle says yes. :)

**Comment by berlintam** [comment]
sorry @1000miles! Ignore the waffle. I was bored one day but it doesn't represent anything at this point. I'm just gonna delete it. Feel free to take a crack at this if you want, or not, everything works :)

**Comment by til** [comment]
#497 is dealing with this.

**Comment by lislis** [comment]
This is now live! Closing
