### ISSUE TITLE
sign in with github?

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#297]
since most/all of our users will use/are using github, maybe it makes sense to change/alter our sign up process to allow users to sign up/into the app using github.

thoughts?

**Comment by FrauBienenstich** [comment]
I like that!

**Comment by berlintam** [comment]
of course you do. I suggested it :smile:

**Comment by PragTob** [comment]
sounds great, devise has oauth capibilities and or there is some gem plugin... and as it happens I'm fighting with oauth right now myself, so I even know some of that stuff =D

**Comment by berlintam** [comment]
http://railscasts.com/episodes/241-simple-omniauth-revised
http://railscasts.com/episodes/235-devise-and-omniauth-revised

**Comment by berlintam** [comment]
http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/

**Comment by FrauBienenstich** [comment]
i pushed a branch that i think is kinda half working....i am gonna leave it like that for now... :zzz:

**Comment by lislis** [comment]
@FrauBienenstich can you send a pull request?

**Comment by FrauBienenstich** [comment]
for shizzle

**Comment by lislis** [comment]
![](http://i.giphy.com/LdnaND03GRE9q.gif)

**Comment by FrauBienenstich** [comment]
here comes a second try! #352

**Comment by berlintam** [comment]
done!
