### ISSUE TITLE
group activity status

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#298]
I talked to Sven yesterday and we talked a bit about our little app.
He suggested that we should somehow indicate if a group is still activly meeting.
I think it makes sense and we didn't think about it yet.

Also related to the #282 calendar feature, that maybe we display a warning to an event if the group hasn't been active for a month or so.

The important question is how to measure the activity. Sven suggested some sort of check-in ('Did your group meet this week?'), but I'm not sure if people would use it.

Thoughts?

**Comment by berlintam** [comment]
hm.... interesting....
maybe we can have an active checkbox...
and then maybe an email can be sent out to the group, once a month, and ask them if they're still active and request that their update their status if they're not. 

alternatively/in addition to this, when people sign up for a group, we should somehow make it clear to them that they should contact the group before going to make sure that they're still meeting. Either via an alert of some kind or an email...
