### ISSUE TITLE
delete a group when it no longer exists

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#301]
admins can delete groups, but if a group decides to no meet no longer, there should be a way

**Comment by sareg0** [comment]
Hey guys,
Just to protect against malicious people that may have fallen out with their group and want to delete it themselves, is the 'delete group' function for non-members on a 'request' basis, or will it be instantly deleted?

Just wanted to make sure I understand what functionality we want on this :)

**Comment by til** [comment]
Apparently deleting a group from the admin dashboard does not work. @sareg0 is on it

**Comment by lislis** [comment]
Since this seems to be merged I'll close this

**Comment by til** [comment]
Yes, I think this is fixed. Thanks @lislis!
