### ISSUE TITLE
Buy/ use a ssl certificate, force https

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#310]
Since we have login-stuff going on, we should encrypt our connection

**Comment by lislis** [comment]
waiting for https://letsencrypt.org/

**Comment by lislis** [comment]
Good news everyone!  
Let's encrypt is here and since we're moving to Uberspace now anyway there is even documentation:
https://blog.uberspace.de/lets-encrypt-rollt-an/  
https://wiki.uberspace.de/webserver:https

**Comment by berlintam** [comment]
such excite!

**Comment by lislis** [comment]
I installed a Let's encrypt cert as described in https://wiki.uberspace.de/webserver:https
The cron that checks/ updates the cert is in place as well. I also enforced HTTPS via the htaccess as described in here https://wiki.uberspace.de/webserver:security.
Sooooo, https://rorganize.it/ :tada: 

Closing this :)

**Comment by berlintam** [comment]
amazing!!!!!!!!!

**Comment by til** [comment]
Very nice, well done!

A small followup, there is a mixed content warning now (on ff at least):

> Blocked loading mixed active content
> http://fonts.googleapis.com/css?family=Pacifico

I haven't looked into it, but if possible, we should use
protocol-relative references - the ones that start with a double slash,
in this case: "//fonts.googleapis.com/css?family=Pacifico".

**Comment by BriocheBerlin** [comment]
Uh, I didn't see this! Great!
:smile_cat:
