### ISSUE TITLE
Security issue with RedCarpet Markdown parser!

### ISSUE THREAD

**Issue by til** [rubycorns/rorganize.it#322]
See http://danlec.com/blog/bug-in-sundown-and-redcarpet

I tried the test on that post by adding the text `_nothing_@danlec.com` in a group description and indeed, it was improperly escaped. So it seems we are vulnerable.

Proposed solution: read the announcements to see if there is a new version that is not vulnerable, if yes, upgrade. If not, see if there is a manual fix that can be applied.

**Comment by til** [comment]
Announcement on the ruby-sec mailing list: https://groups.google.com/forum/#!topic/rubysec-announce/Wrv3vHj5G50

**Comment by lislis** [comment]
argh shit.

**Comment by berlintam** [comment]
it looks like updating it should be enough, hey? https://rubygems.org/gems/redcarpet/versions/3.2.3

**Comment by til** [comment]
Yes, 3.2.3 has the fix they say.

**Comment by berlintam** [comment]
I just updated it at work, and it works.
yaaaay, thanks for the heads up @til!

**Comment by til** [comment]
Cool, thanks! Did you also deploy it, if not, could you?

**Comment by berlintam** [comment]
oh, haha, i mean... a different app... at work. But I can totes do this later.

**Comment by til** [comment]
Ah, hehe, ok ;-)

**Comment by berlintam** [comment]
https://github.com/rubycorns/rorganize.it/commit/272e58304ba5639e3e5b847950b5f9093f463f7f

**Comment by til** [comment]
Cool. Did you also deploy it?

**Comment by berlintam** [comment]
yup - just did.

**Comment by til** [comment]
Thanks!
