### ISSUE TITLE
Can't edit groups although I'm an admin

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#326]
reproduce:
- be an admin
- go to dashboard
- try to edit group

expected:
- groups form

actual:
- 403

**Comment by berlintam** [comment]
Do we want admins to be able to edit groups? Seems a bit shady to me....

**Comment by lislis** [comment]
I think for admins that makes sense. Don't you?

**Comment by berlintam** [comment]
not really.... what would we even do in there?

**Comment by roschaefer** [comment]
Admins don't have [group_member_powers](https://github.com/rubycorns/rorganize.it/blob/master/app/controllers/application_controller.rb#L29) for [action edit ](https://github.com/rubycorns/rorganize.it/blob/master/app/controllers/groups_controller.rb#L7) in the group's controller. Two solutions come to my mind:

1. Don't display the edit button in the admin dashboard. (e.g. ```if current_person.member_of?(group)```)
2. Lift the admins' rights to edit groups (e.g. ```ensure_member_powers``` means you are a member or an admin)

Opinions?

**Comment by PragTob** [comment]
@berlintam I think it makes sense, e.g. if information is offensive or for whatever reason, admins should really be admin imo :)
