### ISSUE TITLE
setup a staging environment

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#331]

**Comment by berlintam** [comment]
:+1:

**Comment by til** [comment]
Oh no, staging servers are so 2010 ... feature flags are the modern way
to go!

**Comment by berlintam** [comment]
like with rollout? https://github.com/FetLife/rollout

**Comment by til** [comment]
or just coded by hand?

render(current_user.fancy? ? :show_new : :show)

**Comment by berlintam** [comment]
`current_user.fabulous_rubycorn?`

**Comment by til** [comment]
all_the_features!

**Comment by lislis** [comment]
Closing this. Does not seem necessary. Or apparently feature-flags are where it's at
