### ISSUE TITLE
updated/remove people that don't need the build notifications

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#336]
In inputting the 'cache' thingee in the travis.yml file I saw that there are a few 'old' email handles, and/or perhaps someone that doesn't need to get the build notifications anymore

You can take a look see
https://github.com/rubycorns/rorganize.it/blob/master/.travis.yml

For example, there is Tobi's student address, and someone person I don't know... Also Lisa's address may also need to be updated. 

Just thought I'd write this up as a small maintenance/admin task that could be easily performed.

**Comment by sareg0** [comment]
Also Lisa said we could potentially have the notifications go to an IRC channel

**Comment by berlintam** [comment]
good point. get rid of those ppl!
or rather... get rid of everyone but rubycorns I'd say.

**Comment by berlintam** [comment]
by rubycorns I mean the rubycorns email address.....

**Comment by sareg0** [comment]
cool! I'm going to mark this as a hack day task :)

**Comment by berlintam** [comment]
solved with https://github.com/rubycorns/rorganize.it/commit/8071001224a7e6c168efe176cc8684dd63e558f5

**Comment by sareg0** [comment]
sweeeeeet!
