### ISSUE TITLE
Add list of Rails Girls coaches

### ISSUE THREAD

**Issue by alicetragedy** [rubycorns/rorganize.it#337]
I'm opening this issue following a brief discussion on the RG team mailing list and an invitation from @sareg0 to add this in here.
On the mailing list, I suggested the idea of having a small app to list Rails Girls coaches that are interested in travelling and helping out/coaching at other Rails Girls events. Ideally the coaches could enter info on which chapters they could coach at (or which region they would be available for), and under which conditions (eg. can pay for own travel/accommodation or not) and of course have their contact information, which would only be visible to registered users. 
Since someone pointed out there was already an app (rorganize.it), made by the rubycorns, listing coaches and study groups, I thought that maybe it could be something that could be implemented here, rather than making a separate app for it. Just throwing this out there – I understand if it's not within the scope of rorganize.it, but before building something somewhere else, I wanted to ask what your thoughts were on this! :+1:

**Comment by til** [comment]
I can't speak for the others, but to me that sounds like it is very well within the scope of rorganize.it, and it sounds like a very useful feature! Much of the needed infrastructure already exists in rorganize.it, and there are some very capable oldtimer rubycorns that could work on the necessary additions - if they want, of course.

**Comment by berlintam** [comment]
sounds good!

**Comment by sareg0** [comment]
The first step of this has now been completed: adding a checkbox to people's profiles, that will hold a boolean for their willingness to coach a workshop.

I am thinking next steps should be to filter the 'people' show page by their 'willingness to coach'

This is of course not ideal, because it's just a big list, with no location of the coaches and no way to contact them

Is this a good way to proceed, or should we approach next steps from a different direction.

**Comment by berlintam** [comment]
so I added this ticket: https://github.com/rubycorns/rorganize.it/issues/353 which asks users for their email address and website. Maybe we can also add location to this. And that will help with your filtering ticket?

**Comment by sareg0** [comment]
cool, good idea. I'll try to take that on next week

**Comment by berlintam** [comment]
This is now further along: I added city, country, & willing to travel to users.
https://github.com/rubycorns/rorganize.it/pull/368

**Comment by berlintam** [comment]
I think this is done! Anyone opposed to me closing it?

**Comment by til** [comment]
I think the way the filter dropdowns work could be improved, but that's a topic for another issue. So yes, close it!

**Comment by berlintam** [comment]
@alicetragedy you can check out the final product here! http://rorganize.it/coaches

**Comment by alicetragedy** [comment]
@berlintam sorry I dropped the ball here! it looks great :+1: and I've already added myself to the list ;) awesome work rubycorns!!
