### ISSUE TITLE
learning resources section

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#339]
have a section that lists learning resources which come RECOMMENDED by the fabulous rubycorns!

**Comment by lislis** [comment]
Is this meant to be part of rorganize or of the rubycorns.club? in case of the first one, please elaborate on how you image it

**Comment by berlintam** [comment]
I guess I was thinking for rorganize it. Or maybe we can have a 'getting started' section, and list off things people can do in a project group, like 'work on the following tutorials which we think we really good' and then list them, or 'contribute to the following open source project which are beginner friendly' and then list them etc....

It would just be a static page which we, as admins, could add to. 

Or perhaps we can expand the groups show pages a bit, and individual groups can add some of their favourite learning resources, which other ppl can then see and use for themselves.

**Comment by til** [comment]
I like the idea of having a space for project group specific learning
materials. Every group is different, and learns different things, some
don't even do ruby but e.g. clojure, so it'd feel wrong to me for us to
impose a global list of recommendations on everyone.

It could be a simple textarea field per group, that is only displayed on
the groups show page when filled out. Of course with emoji and autolink
support!

It would be interesting to see what the various groups put in there! I'd
put in for the rubycorns: http://ruby-for-beginners.rubymonstas.org/ ,
https://www.railstutorial.org/ and http://guides.rubyonrails.org/ (as a
general recommendation for intermediate-ish people).

**Comment by berlintam** [comment]
:+1:

**Comment by berlintam** [comment]
closed w/ #345
