### ISSUE TITLE
change favicon

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#342]
it should totes be the new logo now

**Comment by lislis** [comment]
![asciicorns](https://cloud.githubusercontent.com/assets/1006478/8065289/debdc4be-0ee0-11e5-8fe9-1a5f8f701572.png)
Here is the logo for your downloading pleasure

**Comment by berlintam** [comment]
hm, this just looks like a black box when it's the favicon. is there any way to have it on a white background instead? (what is even photoshop/illustration tools/help)
![screen shot 2015-06-09 at 20 34 43](https://cloud.githubusercontent.com/assets/4237285/8066267/028bbf08-0ee7-11e5-94ce-0e9b30b17b46.png)

**Comment by lislis** [comment]
![asciicorn-transparent](https://cloud.githubusercontent.com/assets/1006478/8066332/61581a72-0ee7-11e5-8336-28deec4be1bc.png)
Here is one with a transparent background

**Comment by berlintam** [comment]
sehr schön

**Comment by til** [comment]
We can haz animated favicon please?

**Comment by berlintam** [comment]
..... IS SUCH A THING POSSIBLE!?

**Comment by til** [comment]
It totally is! There was some kind of spaceship-flight-animation once, but ... ah, found it: http://www.p01.org/releases/DEFENDER_of_the_favicon/

Insanity.
