### ISSUE TITLE
improve user experience

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#347]
Maybe it would be a good idea to give new users of our website a bit of a tour. At the moment, users sign up and are just brought back to the root page, with no explanation. 

Maybe we could have a 'new user landing page' or something, that sort of explains what to do. Like, go join a group, make a group, put what you're working on in your profile, read our blog, etc...

Or perhaps a email to new users would be enough, one that provides links to helpful parts of our site to get ppl started. 

wdyt? 

ps - gifs should be involved in as many places as possible.

**Comment by lislis** [comment]
![seconded](http://i.giphy.com/7LAqMVFxOGPAc.gif)

Very nice idea! A simple this 'here are groups', 'here you can join a group', 'here you can make a group' with screenshots and :cake: should do it

**Comment by berlintam** [comment]
it's all about the cake.

**Comment by lislis** [comment]
of course

**Comment by berlintam** [comment]
let's just have a page with pictures of cake. and then we can close this issue.

**Comment by sareg0** [comment]
OH I LOVE THIIIIIS! I wanna make the app so nice to use, and CSS all the things :D

![yo](http://i.imgur.com/YUxcs8W.gif)

**Comment by berlintam** [comment]
btw, this has been started here: https://github.com/rubycorns/rorganize.it/tree/user-experience
