### ISSUE TITLE
use postgres

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#358]
Shelly uses postgres... and I ran into a problem w/ deployment on tuesday b/c I had written an SQL query for our local database which did not work for postgres! the horror!

anyway, this is more a discussion topic than a hard and fast 'let's do this'. what does everyone think?

@til mentioned that it can be a hassle to set up locally, so there's that to think about.

**Comment by PragTob** [comment]
Yeah we had this topic once before... 

I'm a big :+1: on using postgres locally as dev env should be as close to the production env as possible.

At the same time, though, this is a beginners app where beginners should have an easy time getting started with it which is... well, unfortunate. Installing the postgres gem alone needs some header files and stuff not speaking of the db connection.

If we do it, we should have pretty good documentation for it. Problem I see: I have no idea how to get it setup on Windows (or if that's even possible).

**Comment by til** [comment]
In general I am also in favor of using postgres, but for the reasons
already outlined, I'm against using it for rorganize.it.

There was this one rare case of a migration not being portable between
sqlite and postgres, which, I have to admit, is partly my fault, but I
hope that something like this doesn't happen that often, and if it
happens, that there will be a way to work around it.

I tried to look for a portable way to write the migration in this case,
looked at the documentation of update_all:
http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update_all

and it seems there is a simple way. Either put single quotes around the
boolean: "admin = 't'", or use update_all with a ruby hash right away.
Tam, do you want to try to change the migration with one of these
variants and deploy again?

**Comment by berlintam** [comment]
@til, sure, i'll give it a shot!

and yes, very good points against postgres. ok - thanks for clearing it up :)
