### ISSUE TITLE
Double vertical scrollbar

### ISSUE THREAD

**Issue by til** [rubycorns/rorganize.it#362]
In Firefox, I see two scrollbars on the right border, of which the rightmost one is without functionality, and instead the left one must be used to scroll the page content vertically. The left one looks wrong though. See attached screenshot.

Since we are using a fixed navbar from bootstrap, I think it should instead look like in this example: http://getbootstrap.com/examples/navbar-fixed-top/

It has something to do with the overflow styles that are set on the body. Why are they set on the body? Can we try to remove them?

![ror-scroll](https://cloud.githubusercontent.com/assets/11211/9028205/a5dbdcfc-3970-11e5-90c1-4f016bd74d73.png)

**Comment by PragTob** [comment]
duh. Same here :(
