### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#366]
b/c it's the right thing to do of course!

**Comment by PragTob** [comment]
:+1:

**Comment by sareg0** [comment]
absolutely! Thanks @berlintam I'll close it now that it's added :)

**Comment by PragTob** [comment]
@sareg0 it is not added yet, it is "only" a pull request. Issues should only be closed after a pull request is really closed :)

**Comment by sareg0** [comment]
oops! I didn't mean to jump the gun.
