### ISSUE TITLE
paginate users page?

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#370]
We now have 100 users on our page. This means we have the best app ever. 

Maybe we should think about paginating the people index. Or adding some search by alphabetisation (see all the users who's names start with A, for example). 

Or maybe just a search function. 

Wait a second... I'm getting deja vu....

**Comment by lislis** [comment]
:confetti_ball: :tada: 100 users :tada: :confetti_ball: 
We could have a long list on one page and alphabetical jump links. Or a search of course. I like searches and then pagination.

**Comment by berlintam** [comment]
by 100 I mean 145!

yes, alphabetical jump links is what I meant. much learn etc...

**Comment by PragTob** [comment]
hm I never did alphabetical jump links, just pagination - both seem valid.

Search, of course, is great. However, if we stick with our "sqlite is valid in dev" we can't do the cool stuff as we can't use Postgres features. Then again, with 100 users we probably don't need fancy Postgres features, but Tobi LOVES fancy Postgres features.

**Comment by til** [comment]
I love fancy postgres features as well! But I guess a list up to a
couple of hundreds of items would still be ok nowadays.

Grouping by alphabet is ok, but maybe there is an even better grouping
attribute that is more relevant to visitors - what about grouping by
city?

**Comment by berlintam** [comment]
I love that idea!

But we don't really ask users for their location.... I mean... we do now sort of kind of via the coaching feature, but the average user isn't asked for their location.

**Comment by til** [comment]
Unfortunately, yes. But maybe existing users will update their city
slowly, now that the feature exists?

To expand the grouping idea further - the groups index page could show
the cities as headlines and beneath the first x users of that city. When
the number of users in a city exceeds a certain threshold, it could have
a show more link:

Atlanta
  Anna A

Berlin
  Lisa P
  Tam E
  Til S
  <show more>

Copenhagen
  Smorreprot

etc. ...


This way, the visitors who are interested in members in a specific city
could find what they are looking for already on the groups index page.

**Comment by berlintam** [comment]
I started working on this & I have a question: At the moment we only display people's location to logged in users. So separating the users via city on the index page then becomes a bit difficult.... The way I see it, there's 2 options:
1. show people organized by city for logged out users anyway (I don't really like this option thou, it feels a bit dishonest)
2. show just a standard list of ppl for logged out users & a list organized by city just for logged in users
3. something else

thoughts?

**Comment by PragTob** [comment]
phew tough not to crack indeed. We could also do:

4. just show user location for logged out users as well

Because really, being logged in/registering isn't much of a challenge so it's a very low fence to jump security wise either way. Some people might feel strongly about it so I'd be for the option to just have the filtering for logged in users.

**Comment by lislis** [comment]
This can be closed!
