### ISSUE TITLE
Ability to edit a group just by signing up as a coach

### ISSUE THREAD

**Issue by x3ro** [rubycorns/rorganize.it#371]
I just signed up and registered as a coach for [this group](http://rorganize.it/groups/21). For some reason I seem to be able to edit the group's settings now. Is this behavior intentional?

**Comment by til** [comment]
As far as I remember the discussions on the topic, it is somehow intentional, in the sense that we said: let's think about this later. Maybe later is now, and we should think about it.

The possible solutions I see are: 1) joining a group needs approval, 2) only specific people (who exactly?) can edit group profiles.

An advantage of 1) is that all approved members of a group could still edit it, which I find nice because all members are treated equal. What do the others think?

**Comment by berlintam** [comment]
Ya, I guess this is not ideal. Worst case scenario, someone can just join a group and delete everything. 

I like the idea of everyone being able to edit a group, not just specific people. Maybe ppl can only edit the group after a certain period of time? 

Group approval was also definitely discussed and seen as a good solution, it just hasn't been done yet.

**Comment by PragTob** [comment]
:+1: group approval!

**Comment by BriocheBerlin** [comment]
So what does this mean in terms of work flow? How do we check for group approval?

**Comment by PragTob** [comment]
@BriocheBerlin I guess that we'd have pending requests to join a group that then have to be approved by a member of the group :)

**Comment by BriocheBerlin** [comment]
After talking about it, we agreed to this:
Someone wants to join a group and applies for group membership.
- an email is sent to all existing and approved group members.
- (possibly on the general group site) there is an overview of all pending members as well.
- while being a pending member it is not possible to send a second group join request (validation).
- any member of the group can approve / reject (maybe also admins).
- for now on rejection the join request is removed.

**Comment by lislis** [comment]
I'll close this one. 
We implemented the concept of 'group admins' in afaecf15cd80ddd8e4dabc258ee0b7c18880ad1a which addresses the original problem of joining a group and already being able to edit its info. For more info there is a [post on our blog](https://rorganize.it/posts/introducing-group-admins)

The other issue of approving new members of  a group in the first place is explained in greater detail in issue #449 

Thank you for your attention, here is a sloth for your patience
![sloth](https://media.giphy.com/media/p1pYlUn9k4U1y/giphy.gif)
