### ISSUE TITLE
On github connect, detect if we already have someone with that email address

### ISSUE THREAD

**Issue by PragTob** [rubycorns/rorganize.it#383]
when we do the first github connect (not from the profile page, but also on the start page) we should check if we already have the github email in our database and then "merge" the accounts, i.e. add the github token or whatever we save their in our database to the existing user :)

**Comment by berlintam** [comment]
@PragTob this already works!

For example:
* I have a rorganize account where `provider` is nil & `uid` is nil
* I log out
* I go to the homepage
* I click on `Sign in with GitHub`
* my rorganize account is merged with the GitHub account & the values are saved

hurray!
