### ISSUE TITLE
Bug: "Go to groups" - Link on landing page doesn't work

### ISSUE THREAD

**Issue by Malwine** [rubycorns/rorganize.it#391]
I hope there is no issue already.

If I click this button on the landing page after sign up nothing happens.
![screen shot 2015-10-07 at 21 51 14](https://cloud.githubusercontent.com/assets/5123681/10349224/b391df76-6d3d-11e5-93ee-58e12301a3b8.jpg)

**Comment by berlintam** [comment]
oh the welcome page? It works for me - when signed in & not signed in.

**Comment by PragTob** [comment]
doesn't work for me either. Maybe a FF vs. Chrome thing? It's a link in a button, should be a link styled like a button.

![screenshot from 2015-10-08 19 34 57](https://cloud.githubusercontent.com/assets/606517/10374597/2d4da7b2-6df4-11e5-9dd3-bc0d63471181.png)

**Comment by berlintam** [comment]
https://github.com/rubycorns/rorganize.it/commit/4826912f53642272d9dbd9addb8738eb01a3ebb2

fixed it
