### ISSUE TITLE
Fix a wording issue on profile updating notice

### ISSUE THREAD

**Issue by rousisk** [rubycorns/rorganize.it#396]
Hi all,

I just updated my profile on rorganize.it and spotted two small wording issues in the success notice message:

 "You updated your profile! Please **endulge** in some **cakeand** pat yourself on the back for a job well done."

Anyone feels like fixing this? I'd be more than happy to help if needed :)

**Comment by berlintam** [comment]
oh! good find!
You're very welcome to make a PR for the fix & then **indulge** in some cake once it's merged! :)

**Comment by rousisk** [comment]
hehehe, cake sounds great right now. Or any time for that matter :smile: 

Sure, if no one else volunteers by tomorrow I will make a PR!
