### ISSUE TITLE
rspec: we should use eq everywhere, not eql

### ISSUE THREAD

**Issue by til** [rubycorns/rorganize.it#398]
eq is with type coercion, eql without. Therefore eq is a bit more forgiving, and makes more sense imho, but above all it would be nice to use one version consistently throughout the app.

**Comment by til** [comment]
@berlintam fixed it

**Comment by berlintam** [comment]
indeed! https://github.com/rubycorns/rorganize.it/commit/2cdd89aa4946c75cf761efb2c7b0e5dcc74c5faf
