### ISSUE TITLE
remove empty strings from drop down options

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#399]
<img width="548" alt="screen shot 2015-11-03 at 21 44 32" src="https://cloud.githubusercontent.com/assets/4237285/10921144/246d0b6c-8274-11e5-8a7e-b03af2fb717b.png">

I guess some ppl have entered empty strings for their cities & countries. These should be deleted in the following methods:
* https://github.com/rubycorns/rorganize.it/blob/master/app/models/person.rb#L57
* https://github.com/rubycorns/rorganize.it/blob/master/app/models/person.rb#L61
* https://github.com/rubycorns/rorganize.it/blob/master/app/models/group.rb#L59
* https://github.com/rubycorns/rorganize.it/blob/master/app/models/group.rb#L63

**Comment by lislis** [comment]
No! I included an empty option to have no city selected. It's a feature not a bug!

**Comment by berlintam** [comment]
oh! But there's `include: blank` in there now, which does the same thing. So now we have two options for having no city selected....

**Comment by lislis** [comment]
Ah! Apologies then! `include: blank` makes more sense of course :D
