### ISSUE TITLE
Upgrade ruby version (2.2 or straight to 2.3)

### ISSUE THREAD

**Issue by PragTob** [rubycorns/rorganize.it#403]
We should upgrade our ruby version, right now .ruby-version says 2.1, travis tests 2.0.. we should move that up to 2.2.3 or if we're too lazy wait for 2.3 (est. december) and use that.

Upgrade shouldn't be hard, there were few to non backwards incompatible changes.

**Comment by lislis** [comment]
done via https://github.com/rubycorns/rorganize.it/pull/405
