### ISSUE TITLE
Registration email sends to old URL

### ISSUE THREAD

**Issue by til** [rubycorns/rorganize.it#404]
Oh noes! Thanks @eljojo for discovering this: apparently the link in the email still points to railgsirlsapp.shellycloud.com. Which can be displayed in the browser, but first, it's old and ugly, and second, connecting with GitHub doesn't work from there.

Maybe just grep for railsgirlsapp and find all occurences to see if there are more errors like these.

**Comment by berlintam** [comment]
oh noes!

Also, the email is signed 'Best wishes from the RailsGirlsApp'
