### ISSUE TITLE
add open source licence

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#408]
Ahem, we don't have a open source licence yet. I'd vote for the MIT licence

**Comment by til** [comment]
Good point, rorganize should have a license.

I'd vote for AGPL though (
https://en.wikipedia.org/wiki/Affero_General_Public_License ) - I think
it fits better for this project, as it is a complete application already
that would be used standalone, not a library that needs to be
incorporated into another software system.

E.g. Diaspora is licensed under AGPL as well as far as I know.

**Comment by lislis** [comment]
That is a very smart move!
