### ISSUE TITLE
take out references to shelly cloud (like proudly hosted on...)

### ISSUE THREAD

**Issue by PragTob** [rubycorns/rorganize.it#429]
Because we aren't hosted there anymore :)

**Comment by til** [comment]
Wohoo! Well done!

**Comment by berlintam** [comment]
o m geeeeee!

**Comment by lislis** [comment]
Somewhere on the Uberspace there is a banner generation thing. But I can't find it... :/

**Comment by berlintam** [comment]
donezo! https://github.com/rubycorns/rorganize.it/commit/746029bba425bb1dd7ec98c6ee4bc2b6d40402aa https://github.com/rubycorns/rorganize.it/commit/918bd3cdd07bca7a5863e483dd8e51829ff87e01

**Comment by lislis** [comment]
@berlintam you're on :fire: 
![excited](http://i.giphy.com/e07y5SEwFMDm0.gif)
