### ISSUE TITLE
Sign in with github doesn't work

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#432]
<img width="1135" alt="screen shot 2016-03-05 at 13 21 30" src="https://cloud.githubusercontent.com/assets/1006478/13547624/5a620a62-e2da-11e5-8e37-cd14fb32af5e.png">
I'm getting this ^^ error now :(

**Comment by til** [comment]
Most likely the change from http to https needs to be configured on GitHub somewhere. But where - I couldn't find it in the settings after a quick search?

**Comment by lislis** [comment]
Probably. I guess whoever registered the app on GitHub needs to check. Pinging @FrauBienenstich maybe?

**Comment by FrauBienenstich** [comment]
mh, I just checked real quick under my settings > oauth applications > developer applications. It seems I 'own' rorganize but only for development, i think, since it still says localhost:3000/... in all the relevant fields.

**Comment by til** [comment]
Or @berlintam?

**Comment by berlintam** [comment]
ok, I just updated all the things to https. Maybe it'll work now?

**Comment by berlintam** [comment]
for future: it was in OAuth Application Settings/Developer Applications

**Comment by berlintam** [comment]
Aaaaand I just tried it out. Signing in worked. Not sure if it'll act differently for creating a new account thou....

**Comment by PragTob** [comment]
should be okay until we hear the contrary --> closing
