### ISSUE TITLE
Joining groups is (kind of) broken

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#433]
When I try and join a group I get a 500 error (depending on joining as student or coach). **But** the joining itself still seems to work.

**Comment by PragTob** [comment]
might be because email is misconfigured... (i.e. email kicks off, causes the 500) - I remember I fixed that (or thought I did) but maybe we didn't deploy since then? Please have a look today @til @berlintam :)

**Comment by berlintam** [comment]
fixed with https://github.com/rubycorns/rorganize.it/commit/7c4f698c93d4296b54161218c685b2ffc0d0a4fb
