### ISSUE TITLE
Don't show inactive groups

### ISSUE THREAD

**Issue by Powerglove** [rubycorns/rorganize.it#436]
I made a list with RGB Groups that don't exist anymore/at the moment. Would be great, if they can be taken out of the list:

Rubies in the Woods
Wednesday Ruby
Coding Cats
Rubies on da Cloud
RubyDoobyDoo

**Comment by roschaefer** [comment]
"Rubies in the woods" we are not dead! :D


 

-------- Original message --------

**Comment by Powerglove** [comment]
Info came from Robert ;) But cool, if you are still alive!
