### ISSUE TITLE
maps are broken!

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#437]
It looks like group maps disappeared w/ the switch to uberspace

<img width="1243" alt="screen shot 2016-03-07 at 21 01 21" src="https://cloud.githubusercontent.com/assets/4237285/13581594/de7afc72-e4a7-11e5-8034-f4c0892a83a9.png">

**Comment by til** [comment]
Oh noes!

I'm quite sure this is related to the switch to https. The firefox tools
say, that leaflet, our mapping library, could not be downloaded (see
screenshot).

While we do have protocol relative links, the place where it is hosted
simply does not support https. When going to the link directly:
https://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js you get the "This
Connection is Untrusted" message.

So, let's search for an alternative cdn, or download and host the
leaflet.js ourselves.

**Comment by til** [comment]
![leaflet](https://cloud.githubusercontent.com/assets/11211/13581993/e525b678-e4a9-11e5-9987-d7842d67293b.png)

**Comment by PragTob** [comment]
:+1: good analysis til!

**Comment by berlintam** [comment]
fixed with https://github.com/rubycorns/rorganize.it/commit/54cccf7693f3472487b78bd7e8858ec45a17f18f & https://github.com/rubycorns/rorganize.it/commit/ca2af9efb0ff989df6be34761d523deb30dd0053

**Comment by til** [comment]
:+1: good fix tam!
