### ISSUE TITLE
waaaaah best admin dashboard ever gif section also broken

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#438]
<img width="438" alt="screen shot 2016-03-07 at 21 10 51" src="https://cloud.githubusercontent.com/assets/4237285/13581833/3051bbb6-e4a9-11e5-851f-6c00ce6380ef.png">

:cry:

**Comment by PragTob** [comment]
might also be related to the https switch as til explained before - it's mixed content, we can only include content from https:// sites, our link might be wrong or not possible at all. Please investigate today!

**Comment by berlintam** [comment]
fixed! https://github.com/rubycorns/rorganize.it/commit/d208a6769ad29b9589c130f1caebdd2a907ff14b
<img width="443" alt="screen shot 2016-03-08 at 19 34 57" src="https://cloud.githubusercontent.com/assets/4237285/13611851/e9b1bd7a-e564-11e5-87b2-98083890019c.png">
