### ISSUE TITLE
Uberspace emails

### ISSUE THREAD

**Issue by BriocheBerlin** [rubycorns/rorganize.it#443]
So we started discussing this in #392.
Who should get the Uberspace emails? @lislis suggested roar@roganize.it aka the mailinglist. 
But maybe thats a little to public? Or no one will feel responsible...

**Comment by lislis** [comment]
We can also have multiple people. 
I would also volunteer as the mails from uberspace are mostly money related

**Comment by lislis** [comment]
I put my private email in the `~/.qmail` file. Whoever else wants to get the emails can just edit the file and add their email in a new line.
Closing this.
