### ISSUE TITLE
UX Changes - Let's improve the app

### ISSUE THREAD

**Issue by Malwine** [rubycorns/rorganize.it#444]
Dear Corns,

:warning: I got an alarming feedback. I invited someone to take a look at our app to join a group. This was the feedback:

>  Aber die rubycorns sind wohl nicht mehr aktuell?

When I asked for more details why the person thought that: 

> Ich dachte, die Rubycorns seien nicht mehr aktiv, weil auf rorganize nur steht "founded: 2013" und bei den "topics already covered" so wenige Topics zu finden sind. Also nahm ich an, wenn ihr seit 2013 nur 4 Topics hattet (davon eins "Kuchen mitbringen"), sei es nicht mehr aktuell. 

We have a beautiful design from Justine for the UI changes and I think we should also discuss UX.
With this issue I want to invite you to start a discussion on what we can to better on the UX side of our project.

**Questions:**
- Do users find the information they need to join and find a group? Especially the exact location?
- Do users see if the groups are meeting at the moment?
- Is it easy to contact the group?
- What are the barriers?
- Should we just show the topics if the group has topics?
- The map is only working on reload. Should we fix this? Maybe we can find another way of showing the location?
- Should we offer the app in different languages? Use translations? (At least we should offer the homepage in German)

**Comment by lislis** [comment]
> Do users find the information they need to join and find a group? Especially the exact location?
Probably not. We should go over what we have and what we know is missing

> Do users see if the groups are meeting at the moment?
Not really. It's probably best to sort out inactive groups from the main list and also think about indicating group status on the show page.

> Is it easy to contact the group?
We only have mail per group. Should we think about having internal messages? Or sending out emails to all members of a group?

> Should we just show the topics if the group has topics?
TBH, I think the topics are useless. Does anyone know if groups are using those?

> The map is only working on reload. Should we fix this? Maybe we can find another way of showing the location?
When did that happen?! It was working at some point and we should totally fix it. Plus showing the address somewhere.

> Should we offer the app in different languages? Use translations? (At least we should offer the homepage in German)
That's a giant beast. But might be a good idea in the long run.

Overall, it might be useful to send out a survey to people asking for the info we need?

**Comment by til** [comment]
This is important feedback, thanks. Some parts of it are small and could
be fixed independently - may I suggest that you create separate issues
for those, or link to existing ones? It's always rewarding to have
smaller tasks that can realistically be moved to a DONE state. E.g. to
fix the map. There is already #449 dealing with the group join process.
There is #157 and #446 dealing with a part of how to contact groups.
There could be an issue about the topics feature ...

**Comment by Malwine** [comment]
Another point we discussed later with Brigitte and Sara:
Before we changed the name to `rorganize.it` we were called `RailsGirlsApp`.
With `RailsGirlsApp` the focus on RailsGirls groups with female* attendees was more clear. We need to find a way that groups can communicate if they provide a special learning athmosphere for a certain group of people.

@til :+1: for making small issues. This issue here should just be a collection of thoughts.

**Comment by Malwine** [comment]
@lislis :+1: for a feedback round

**Comment by lislis** [comment]
I started sketching up a new group show page. I'll just leave this without further comment :P
![20160712_002](https://cloud.githubusercontent.com/assets/1006478/16780370/af2f5e8a-4876-11e6-9943-162661e524dc.jpg)

**Comment by sareg0** [comment]
We underwent a redesign in 2017. Therefore, i am going to close this issue up. Perhaps we could open a new one with suggestions for UX based on the new design. Please also reopen if you still feel like it is current and work-on-able
