### ISSUE TITLE
Joining a group :sparkles: a draft :sparkles:

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#449]
OK, so here is the proposed workflow:
- user goes on the group page, there is only button that says "join the group"
- the user clicks the button and a message field opens with a default message like `I want to join your group as student`. the user can edit the message. There is also an explanatory text that says that the message will be send to the group for approval. And there is a "request membership" button.
- the user clicks the "request membership" button. The message field closes with a notice "Your request was sent to the group." and there is now a "membership pending" indicator instead of "join the group". 
- In the background an email is sent to the group_email and the pending membership is shown. On the group page as pending membership. duh.
- a member of the group can (un-) approve the membership. (nice to have: send an email to the new member)

**Comment by til** [comment]
I like it!

However I want to warn, that this is not a trivial feature, so don't
expect to be able to implement it in half an hour ;-)

Also, it would be a great opportunity to practice developing guided by a
feature spec (aka integration test, aka end-to-end test, aka functional
test). Part of it is sending out the emails. Check out topic 10.3 in
http://guides.rubyonrails.org/testing.html .

With ActionMailer::Base.deliveries.last it should be possible to access
the latest sent email, and check its contents, somehow like this:

join_notification = ActionMailer::Base.deliveries.last
expect(join_notification.subject).to eq('Erna Example wants to join the Rubycorns')

**Comment by berlintam** [comment]
cool!

Can any of this be broken down into smaller tasks? Then we can all work on it together! #teamwork #rubycornsrule

**Comment by sareg0** [comment]
We closed this PR just to keep things nice and clean: https://github.com/rubycorns/rorganize.it/pull/456

However, we can re-open it if needed.

**Comment by lislis** [comment]
I'm tackling this now in PR #648
