### ISSUE TITLE
THIS WEEK: BEGINNERS MAY ATTEND

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#458]
As a quick heads up, we may have beginners from the Rails Girls workshop in attendance.

We should make this clear that we will have a new beginner's batch start on Tuesday 26th April, and what topics/curriculum/exercises they will be starting with.

- [ ] mailing list
- [x] twitter (also how to join the group)
- [ ] on rorganize.it

We should expect to need to give them more coach time, and perhaps make a beemer available so that they can go through things together. 

If someone could take a task each that would be wonderful. Just tick it off once you've done it :)

@til perhaps you could tell us as to what you might cover with a beginner/s, either here or via the mailing list, so we can mimic that in our tweets/updates to the group on rorganize.

Many thanks to all!

**Comment by berlintam** [comment]
👍

**Comment by til** [comment]
Cool!

As for the curriculum, what about following
http://ruby-for-beginners.rubymonstas.org/ ? Do you know if the
rubymonstas use it as curriculum, and if so, how exactly? Does the group
read the text parts together,
http://ruby-for-beginners.rubymonstas.org/variables/right_goes_first.html
- or are they supposed to have read the text parts on their own, and
only go through the exercises in the meetings? It seems the exercises
are undergoing a rewrite currently, the new part is not complete yet.

**Comment by sareg0** [comment]
I think they do use it as a curriculum, but I wonder if their coaches might be able to give us a few more details. I will write to Sven and the others I know in the group, or ping their mailing list to ask how they do it.

Do you feel like you would like to use that curriculum @til or do you have another one you like to follow?

In the exercises part they recommended doing Try Ruby first if you haven't already (http://ruby-for-beginners.rubymonstas.org/exercises_2.html), so perhaps we could try to get through Try Ruby. We did not do it at the workshop in my group, just some other basics, so it could be new curriculum for them. . 

I think it might be good to have a little check in with them about why they are coming and what they're hoping to get out of learning Ruby/programming; that might also help to set the tone and pace of their learning. Maybe they want to move on to creating their own app asap, so you might move on from the Ruby basics quickly with that focus.

PS. I'm not sure if any beginners will come, but wanted to try and be prepared if they do :)

**Comment by sareg0** [comment]
Also, I found Learn Ruby the Hard Way a particularly good resource, so that is another option as you have chapter by chapter steps you could take: http://learnrubythehardway.org/book/intro.html

**Comment by berlintam** [comment]
This one is also super good! I did it like 10 times when I started with ruby http://tutorials.jumpstartlab.com/projects/ruby_in_100_minutes.html

**Comment by til** [comment]
Those are all great resources, thanks for sharing! And yes, it's a good
idea to first ask what they are aiming for, and maybe adjust the
material based on that. If someone want to write their own app and have
already concrete ideas, that's great, but I'd also mention that it is
important to learn some ruby/programming basics, in order to not get
frustrated when trying to accomplish things in rails or another web
framework.

An advantage of following ruby-for-beginners would be that they can
easily switch between rubymonstas and rubycorns, if they want. But I'm
not sold on using it. Ruby in 100 minutes is really good too. Not sure
about ruby the hard way yet, I'll have to look more into it.
