### ISSUE TITLE
Who can read topics

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#481]
We never actively decided how this should work, so let's do it now.

**Old state:** topcis were listed on the main group page. Everyone could see it, members could administrate

**Current state:** topics live nested under groups, only members can acces then at all

**Wanted state:** ???

**Comment by katrin-k** [comment]
I think it should be possible for non-members to read topics. From the perspective of interested learners searching for a group, topics give a good hint on what is actually happening in a group.

**Comment by til** [comment]
I also think that topics should be readable for everyone, and also their comments.
