### ISSUE TITLE
Sign up should show "Sign in with Github" as an option

### ISSUE THREAD

**Issue by katrin-k** [rubycorns/rorganize.it#482]
The page https://rorganize.it/people/sign_up should also show the option to sign in with Github. 

The condition in `devise/shared/_links.haml` currently says `- if devise_mapping.omniauthable?`. Can this be extended to also show on sign up?

**Comment by lislis** [comment]
@katrin-k 
<img width="285" alt="screen shot 2016-11-29 at 21 03 35" src="https://cloud.githubusercontent.com/assets/1006478/20726803/5706e010-b677-11e6-8313-233c2ce34c1c.png">
on current master I see this ^
Is this what you mean? it's not pretty but it is there

**Comment by katrin-k** [comment]
oh dear… this is embarassing…
I've removed it myself during template redesign…
thanks for looking it up @lislis 

*off, quitely mumbling and silently closing this issue*
