### ISSUE TITLE
Add "change password" option

### ISSUE THREAD

**Issue by katrin-k** [rubycorns/rorganize.it#483]
On the user profile page, I've added a button to "Change the password" (see https://github.com/rubycorns/rorganize.it/commit/9162c39936064aa13c53bfddfda3f624e0aca270). However, I was not able to figure out the correct url_path. 

It might also make sense to only show this option if the account is not linked with Github?

**Comment by til** [comment]
Rails has a rake task that shows all routes of an application:

bin/rake routes

Each line is a route, and the column of the left has the corresponding
path helpers part, but without the _path or _url ending.

Searching for "password" in this output

bin/rake routes|grep password

returns among other things "edit_person_password", so maybe
"edit_person_password_path" is the right one? I didn't try it though.

And yes, only showing that when not connected through GitHub sounds
sensible to me.

**Comment by raluka** [comment]
In current implementation, we allow an user to change password only through devise (as request provided via email). We can add option to change password in `edit` form for user, or in separate form. Also, we need to update controller to know about that (either `update_user` method, or create a separate method `change_password`)

**Comment by katrin-k** [comment]
@raluka \o/ thanks!  Changing pw works sweetly. 
However, I do have a little problem finding the corresponding html (it needs adjustment to the new design). The routes table hints at `edit_person_registration_path 	GET 	/people/edit(.:format) 	registrations#edit`. But this… is not there? Yet… it does serve an html?

**Comment by til** [comment]
This is an interesting question. We were looking for the corresponding
view as well yesterday, and didn't find it. Maybe they are still inside
the devise gem and need to be re-generated, following the procedure at:

https://github.com/plataformatec/devise#configuring-views

- maybe you want to try that?

We would have liked to remove the field for email, because we don't want
to allow changing the email for now, so if you find the view, please
remove it or let us know.

**Comment by katrin-k** [comment]
Booyaka! 
This was indeed the reason. And: nice gem, worked pretty easy. Thanks for the link, @til!
I've only run it for the `registrations` and converted the generated file to haml. Will adjust the html and send the PR then.

**Comment by katrin-k** [comment]
Redesign is done. This can be closed.
