### ISSUE TITLE
Tests to add

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#496]
A list of nice things in our app that are not tested (yet).
But it would be nice if we did :)
Feel free to add more!

- [x]  The current user's profile gets a highlighting class in the people overview

**Comment by sareg0** [comment]
ohh! I'm gonna take this, cause I need to get better at testing... writing them, and so on :)

**Comment by til** [comment]
Haha, first to check the checkbox, but all credits to @sareg0 for adding the spec. Should we leave this issue open and add some more specs that are missing, if yes, can you suggest some?

**Comment by sareg0** [comment]
@lislis agreed that we will close this issue since the test we wanted to add has been added. We'll open new ones later for new things to test :)
