### ISSUE TITLE
Groups overview: Filters for sub navigation

### ISSUE THREAD

**Issue by katrin-k** [rubycorns/rorganize.it#522]
On the groups#index page, add more filters for sub navigation (e.g. show recently added groups, inactive groups, mixed groups). 

What are good/useful options?

**Comment by lislis** [comment]
I like it!
How about
`All groups | New groups (added in the last two months or so) | Mixed groups | Groups searching | Inactive groups`

`Groups searching` could be all groups that have one of the :soon: available searching tags. Or we could split that up in `Searching for students| coaches | meeting place`

**Comment by lislis** [comment]
So, searching statuses shipped.
We could now have routes that list groups depending on the status (or tags)

**Comment by blackknight75** [comment]
@lislis has this issue been taken care of?

**Comment by lislis** [comment]
@blackknight75 nope, not yet. Would you like to tackle it?

**Comment by lislis** [comment]
Closed by #585 and #627
