### ISSUE TITLE
Coaches: Link back to "all coaches" list

### ISSUE THREAD

**Issue by katrin-k** [rubycorns/rorganize.it#524]
The people overview (file: `views/people/show`) has "all people" and "workshop coaches" as sub menu items. When clicking on a person profile and then clicking back to the list, the current user flows are:

1) home > people > (all people is loaded) > single person > link back: all people
2) home > people > (all people is loaded) > workshop coaches > (list of workshop coaches is loaded) > single person > link back: all people

In 2), the link back should load workshop coaches. (= It should basically be the same as the back-button of the browser)

Previously, there has been a condition `if request.request_uri = /coaches …`, however, this method is not working (anymore). 
This could be done with JS, but a Rails solution would be better, I guess. 

Also, @til raised the following concern: Once you click the menu item "workshop coaches", the coaches_path /coaches somehow has to be remembered by the app. For how long should the app remember this path? Just this one click into a person profile? Or for longer (e.g. when a user clicks their way further to a group profile or to edit the profile and then wants to go back)?

I think, it's fine to just remember it 1 click level down.

**Comment by lislis** [comment]
Other suggestion: 
Can't we just keep the sub navigation that is on `all people` for all people pages? Then it would be consistent and also act as a kind of (not really) bread crumb and we don't need to go down a path remembering 🐇 🕳

**Comment by til** [comment]
I'm totally in favour of making it static, the same for all people
pages. There is no need to replicate the functionality of the browser's
back button. It would be unnecessarily complicated.

**Comment by lislis** [comment]
Current state: we're using static links for people right now ('All people' and 'Workshop coaches')

Once we have more categories of people we can add them to the subnav.

Closing this!
