### ISSUE TITLE
Show filter options

### ISSUE THREAD

**Issue by katrin-k** [rubycorns/rorganize.it#525]
On the groups and the people overview pages, there is this city/country filter. 
Once a user sets a filter, this selected option is not shown anymore. 

The minimum should be: the form shows the selected option.
Bonus: The headline "Groups overview" is changed to "Groups overview: Filtered by <selected option>"

**Comment by lislis** [comment]
Started PR #613

**Comment by lislis** [comment]
Also applying this to people overview in #628

**Comment by lislis** [comment]
Both are merged! Closing!
