### ISSUE TITLE
City with more than one name

### ISSUE THREAD

**Issue by dondonz** [rubycorns/rorganize.it#535]
Hello,

In the Groups page, the City filter has two Berlins - one is lowercase ('berlin'), the other is capitalised ('Berlin'). I'd like to change it so that there can only be one name for every city.

I'm guessing there is a pre-save or pre-validation method for this. I'm happy to look into it. We will need to also manually change the 'berlin' groups to 'Berlin' from the console once this is complete.

**Comment by til** [comment]
Cool, thanks for reporting and for looking into it! There really should
only be one Berlin.

**Comment by lislis** [comment]
After talking to @til there are two things we need:

1) clean up the production database to only have each city once
2) write some code that prevents duplicate city names in the future

@dondonz would you like to tackle 2)?

**Comment by dondonz** [comment]
Yes I'd love to!

**Comment by lislis** [comment]
closed by https://github.com/rubycorns/rorganize.it/pull/542
