### ISSUE TITLE
Filter option ordering

### ISSUE THREAD

**Issue by dondonz** [rubycorns/rorganize.it#536]
Howdy,

At the moment, filter options for city and country are being displayed in the order they appear in the DB. Shall we specify an order, to make it easier to see if there is a group in a particular city or country?

For cities: how about we order these alphabetically?

For countries: shall we order this alphabetically, or by some other rule?

**Comment by til** [comment]
Good point. I think any order would be better than the current one -
alphabetically also for countries is totally ok.

**Comment by ZackTaylor** [comment]
@dondonz I'd like to take a shot at this. What controller is this in specifically? And should I order them alphabetically?

**Comment by berlintam** [comment]
looks like this is done!
