### ISSUE TITLE
remove turbolinks?

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#537]
I'd like to remove turbolinks. 
It makes dealing with JavaScript load events harder than it should be (see the maps on group#show).
Any opinions?

**Comment by PragTob** [comment]
Yes please.

**Comment by til** [comment]
Yes please from me too.

**Comment by lislis** [comment]
PR here https://github.com/rubycorns/rorganize.it/pull/539

**Comment by lislis** [comment]
closed by https://github.com/rubycorns/rorganize.it/pull/539
