### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#545]
so that newcomers know where to start :)
Good example
https://github.com/Manishearth/rust-clippy/blob/master/CONTRIBUTING.md

**Comment by sareg0** [comment]
This is a really good idea. We have some newcomers, and it's really nice to know how to contribute... Also when they read the guidelines and want to improve them it's a really nice place for them to start contributing \o/

**Comment by sareg0** [comment]
We have some info on contributing in the `README.md`. Should I add more there or does a new file provide some added benefits?

**Comment by lislis** [comment]
If we add a file named `CONTRIBUTING.md` GitHub will automatically pick it up and it will totally boost our community profile https://github.com/rubycorns/rorganize.it/community :P

**Comment by sareg0** [comment]
I have added this now. BUT it would be great to have more in the contributing guidelines. Happy to get improvements. I will close this issue now, and thank @lislis for bringing it up!!
