### ISSUE TITLE
what is `can_join_group` supposed to be doing?

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#548]
I found this delightful piece of code

https://github.com/rubycorns/rorganize.it/blob/master/app/models/person.rb#L121

Anybody knows or remembers what is supposed to go here?

**Comment by til** [comment]
It works together with this:

https://github.com/rubycorns/rorganize.it/blob/master/app/models/null_person.rb#L7-L9

This NullPerson is instantiated and returned as current_person when
someone browses the site without being logged in. So a non-logged in
user can not join a group, all others can.

**Comment by vsmart** [comment]
I think this can be closed! :balloon:
