### ISSUE TITLE
Regression in top bar vatar styles

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#552]
looks like this now
![selection_008](https://cloud.githubusercontent.com/assets/1006478/26680861/46d8d7d0-46db-11e7-9d45-161e790d29eb.png)

The avatar and user name are no longer on the same (visual) line

**Comment by m-gb** [comment]
Hi there!
I attended Rubycorns and Rails girls a few months ago and came across this.
I just submitted PR #560 for this issue.
Hope this helps.

**Comment by lislis** [comment]
Closed by #560 Thank you!
