### ISSUE TITLE
Logo SVG displayed too big on Mac OS X Safari 

### ISSUE THREAD

**Issue by fanaugen** [rubycorns/rorganize.it#557]
The screenshots are from 18. July 2017 on Safari 10.1.1:

![screen shot 2017-07-18 at 07 57 20](https://user-images.githubusercontent.com/1446237/28302725-6d737f52-6b8f-11e7-893f-5c3cb34d7d38.png)

![screen shot 2017-07-18 at 07 57 47](https://user-images.githubusercontent.com/1446237/28302729-6f9c4e26-6b8f-11e7-8550-30d35e3f4577.png)

**Comment by lislis** [comment]
@fanaugen thanks for reporting!
@sareg0 do you want to give this a shot?

**Comment by sareg0** [comment]
woah!!! Yes! Imma fix it quick smart.

**Comment by sareg0** [comment]
@fanaugen that should be fixed up now. Thanks once again for spotting it!

**Comment by fanaugen** [comment]
@sareg0 yep, fixed! Thank you.
