### ISSUE TITLE
Lists of coaches and students are out of order

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#562]
![selection_014](https://user-images.githubusercontent.com/1006478/29581043-4c303b82-8778-11e7-82a1-1c98e87bf917.png)
![selection_015](https://user-images.githubusercontent.com/1006478/29581044-4c33b618-8778-11e7-912f-cdb4233e8f70.png)

The group#show displays a student and coach title but then lists the people just under coaches.
This can be fixed by moving the list of students under the student headline and above the coach headline.

**Comment by ZackTaylor** [comment]
@lislis this would be my first contribution but id like to try to fix this.

**Comment by lislis** [comment]
Hi @ZackTaylor go for it! Let me know if you need any help!

**Comment by ZackTaylor** [comment]
@lislis for some reason I'm getting the following error when I try to bundle: 
`rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.3.1
  2.3.3
`

**Comment by til** [comment]
Which ruby version do you have installed? It should use 2.4 for
rorganize. Check with:

$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

If that looks correct, maybe you need to install the bundler gem first:

gem install bundler

**Comment by ZackTaylor** [comment]
i figured it out had to run gen install rails odly enough to get bundle working.

**Comment by ZackTaylor** [comment]
@lislis I made a pr for this fix! #564

**Comment by lislis** [comment]
@ZackTaylor thank you! I've merged and will deploy asap!
