### ISSUE TITLE
Tests are order dependend

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#563]
We see an increased number of builds failing on Travis for no apparent reason. Most of the time restarting the respective job fixes the thing. 
This means our tests are borked. Not good

**Comment by vsmart** [comment]
Should we reopen https://github.com/rubycorns/rorganize.it/issues/554?

**Comment by til** [comment]
Ha, yes, I totally forgot that we already had this issue ... sigh.

Closing this in favour of #554, @lislis I hope you don't mind.
