### ISSUE TITLE
Remove GitHub fork ribbon

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#568]
I'd like to remove the Fork on GitHub ribbon.
It doesn't really fit the style anymore and we have a link to GH in our footer (which the ribbon overlays).
Opinions?

**Comment by til** [comment]
:+1:

**Comment by lislis** [comment]
removing here https://github.com/rubycorns/rorganize.it/pull/575

**Comment by lislis** [comment]
merged #575
