### ISSUE TITLE
Cache geocoder results

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#570]
I just needed to set this up for a different project that hit the Google geocode API limit.
We don't make super heavy use of maps but maybe it's interesting to some to try it out?
I followed this guide https://github.com/codeforamerica/ohana-api/wiki/Customizing-the-geocoding-configuration but it's very Heroku specific (other project runs on Heroku) but maybe we can get it to run on Uberspace as well.

**Comment by vsmart** [comment]
If we're hitting google api limits, might I suggest the Mapbox geocoding api? 😇 It's free up to 50000 requests a month. https://www.mapbox.com/geocoding/
I'd be interested in working to set that up!

**Comment by lislis** [comment]
@vsmart do you want to set this up then?

**Comment by vsmart** [comment]
@lislis Yes! Could you point me to where we use the geocoding part at the moment in the code? I'll work on this next week!

**Comment by til** [comment]
As far as I can see, it's only used in Group for the group address,
through the geocoder gem:

# app/models/group.rb:49
geocoded_by :location

**Comment by lislis** [comment]
for reference, this is the config I added to Slam Alphas
https://github.com/rubymonsters/slam-alphas/commit/e848fb4a4dd09781bfb5ff20c0cea6836b6e06d1#diff-05a4c8e202d7bccb52a2b0b16190ca7f

The article I linked to above also lists mapbox as provider, so this should be similar
