### ISSUE TITLE
Batch remove members or at least not redirect to home.

### ISSUE THREAD

**Issue by rojosinalma** [rubycorns/rorganize.it#582]
Hi,

When managing members as an admin of a group, I'd like to be able to delete many members at the same time or at least be able to delete one by one without being redirected to the home.

I was just cleaning up the [group I belong to](https://rorganize.it/groups/contentful-to-be-named)  today, where there's like 40 people who don't actually attend and found this very annoying.

I will push a PR sometime over the weekend anyway, this is just for the formality of reporting it and giving context :)

**Comment by lislis** [comment]
Hey @elfenars, sorry for the long silence!
I can see how this very annoying, thank you for brining it up and working on it. 
I'll assign you to this ticket for the time being. If you want to give it to someone else just holler :)

**Comment by sareg0** [comment]
oh, I would like this because I'd like to clean our group a bit, from people who don't attend much anymore. @elfenars did you happen to make any progress on this?

**Comment by rojosinalma** [comment]
Sorry for being three years late, I'll close this as it's old and it won't be worked on.
