### ISSUE TITLE
Main nav items are too close together

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#593]
Seems the 
```
.main-nav li a:first-of-type {
    padding-left: 0;
}
```
is too much here? Inheriting from somewhere else.

**Comment by DanielAmah** [comment]
@lislis I will love to take fix this bug.

**Comment by lislis** [comment]
@DanielAmah Awesome! Go for it!

**Comment by DanielAmah** [comment]
I have fixed it @lislis

**Comment by DanielAmah** [comment]
Hello @lislis I have raised the PR can you look into it thanks a lot

**Comment by DanielAmah** [comment]
Still waiting for a review @lislis

**Comment by lislis** [comment]
@DanielAmah No need do double post, I'll get to things when I find the time :)

Closed by #600
