### ISSUE TITLE
Can't find arrow images

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#594]
After deploying a change we notice that some images were coming up 404

<img width="1192" alt="screen shot 2018-01-16 at 21 52 38" src="https://user-images.githubusercontent.com/1307818/35011787-b1d98846-fb07-11e7-9b47-5f78b2f1604f.png">

Locally the path is `/assets/select-arrow-flipped.png`, but it looks like the image is in the folder `/assets/images/...`

Is this an asset pipeline thing? Either way, we wanted to report it so we can fix it! \o/

**Comment by lislis** [comment]
Hack-ish work-around #594
