### ISSUE TITLE
Add github handle to person profile

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#596]

**Comment by Seunadex** [comment]
@lislis I'll like to take this up

**Comment by lislis** [comment]
@Seunadex awesome! Let me know if you ave any questions or run into problems :)

**Comment by Seunadex** [comment]
@lislis I have a PR up already, kindly go through it, test and give me feedback, `https://github.com/rubycorns/rorganize.it/pull/598`

**Comment by Seunadex** [comment]
@lislis Kindly review/check the functionality

**Comment by lislis** [comment]
@Seunadex Sorry for the delay, finding time is hard sometimes :sweat_smile: 
I reviewed your PR and left some comments. But already looks very good!

**Comment by Seunadex** [comment]
@lislis yeah i understand, i will address your comments ASAP

**Comment by Seunadex** [comment]
@lislis All your comments have been addressed.

**Comment by lislis** [comment]
I merged the PR, thank you for implementing this!
