### ISSUE TITLE
Misleading profile picture form (on user profile edit page)

### ISSUE THREAD

**Issue by vsmart** [rubycorns/rorganize.it#603]
![screenshot from 2018-02-07 00-01-07](https://user-images.githubusercontent.com/2796920/35889010-2230ba9a-0b9a-11e8-97a6-aacaf4a881e9.png)

The avatar form prompts the user to 'add a picture' even when there already is one. 

It should ideally indicate that a picture was previously uploaded and give an option to delete it.

**Comment by lislis** [comment]
started PR here #612

**Comment by lislis** [comment]
This is live!
