### ISSUE TITLE
Query Optimization in pages_controller and dashboards_controller

### ISSUE THREAD

**Issue by noordean** [rubycorns/rorganize.it#605]
<img width="601" alt="screen shot 2018-02-11 at 12 21 54 pm" src="https://user-images.githubusercontent.com/14357823/36072920-37b376f0-0f28-11e8-9bf3-ff41cd28fbef.png">

Looking at the code above, instead of using `Group.all`, only the needed columns which are `address`, `latitude` and `longitude` can be selected, this reduces the memory space `Group.all` consumes. Also `@people` is not being used anywhere in the `index` view, so it's probably not being used, and so not needed. Changing the active record `.count` to `.length` would also be another optimization as this is being used on already loaded records, `.count` therefore makes another query to count, whereas `.length` wouldn't. Similar cleanups can also be done in the `dashboards_controller`.
I would like to know if to go ahead with this.

**Comment by PragTob** [comment]
👋 

Hi there, thanks for your interest and thanks for your suggestions! 🎉 

1. selecting only the relevant columns is a good observation, although I doubt it's a performance problem we're currently having. We have no performance monitoring although with the advent of skylight for open source we could/should change that. So for now I'd put it in the realm premature optimization although not entirely opposed :)
2. seems like `@people` can go, yes 👍 
3. I believe `count` vs. `length`/`size` makes no difference here as the records shouldn't be loaded at this point, so both just do a `count` query. Imo we can also get rid of `@groups_count` though and just call `size` in the view

The biggest performance optimization I see here though is not loading all memberships and instead just doing a count of them in the database, possibly with a `group` :) Way less records and less work for the database.

**Comment by noordean** [comment]
I get your points @PragTob, and they really make sense.
I have a concern on the memberships's issue, I think doing a `count` on them will now split the query into two, count StudentMembership and count CoachMembership, would this be more efficient than having a single query that gets everything? can you shed more light on this?

**Comment by PragTob** [comment]
👋 
Yes it'd make 2 queries in this case. It'd still likely be more performant (barring a benchmark) - as way less data is needed to be fetched from disk, send around and instantiated on the rails side (memory bloat).

However, you can also get the same result with one query using [`group` combined with `count`](https://stackoverflow.com/questions/7131109/order-by-result-of-group-by-count).

**Comment by noordean** [comment]
Cool. I will get a PR up for this.
