### ISSUE TITLE
Refactor groups controller once app runs on Rails 5

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#611]
On line 
https://github.com/rubycorns/rorganize.it/blob/master/app/models/group.rb#L55
I put in a direct sql query since Rails 4 (or rather ActiveRecord) didn't have an `.or` available yet.

After the app is upgraded to Rails 5 (aka #588 is closed) we can refactor the query to use `.or`.

**Comment by Seunadex** [comment]
@lislis I have a PR up for this issue, kindly take a look at it when you can.

**Comment by Seunadex** [comment]
@lislis I think this issue can be closed now.

**Comment by lislis** [comment]
True! thanks again!
