### ISSUE TITLE
Consolidate 'All groups' and 'Active groups'

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#615]
After seeing the new group subnav in action with our production data I fist of all notices a bug where the groups listed in `All groups` and `active groups` are switched. 
But Instead of 'just' fixing that I think after all it does make sense to link the overall 'Groups' link to `groups#active` (the real active) and get rid of the overview of all groups. 
This would then mean that `recently added` and `searching` are effectively filters for `Active groups` and `Inactive groups` shows all groups that are not in `active groups`.
Does that make sense?

**Comment by vsmart** [comment]
>  But Instead of 'just' fixing that I think after all it does make sense to link the overall 'Groups' link to groups#active (the real active) and get rid of the overview of all groups.

:+1: Would you name that heading 'active grous' or 'all groups' ? I think both make sense. 

> This would then mean that recently added and searching are effectively filters for Active groups and Inactive groups shows all groups that are not in active groups.

:+1: I think we should have the "active" filter implicitly added everywhere - so when I look for recently added, I really want "recently added" AND "active". 

One other point - I noticed there are 0 groups "searching" at the moment. Does that sound right? :thinking:

**Comment by lislis** [comment]
Addressed in #627

**Comment by lislis** [comment]
Done!
