### ISSUE TITLE
Create group without current_person is broken

### ISSUE THREAD

**Issue by vsmart** [rubycorns/rorganize.it#617]
The site provides the option of creating a group without being signed in. 

When I attempt to create a group not signed in, I get an error: 

from https://github.com/rubycorns/rorganize.it/blob/master/app/controllers/groups_controller.rb#L28

```

NoMethodError at /groups

undefined method `join!' for nil:NilClass
```

because `current_person` is `nil`. 

So possible solutions are:
1. disable the option to create a group without being signed in? 
2. add a code path that just creates the group, no user associated 
3. forces the user to also create a user-account while creating a group

**Comment by vsmart** [comment]
@lislis @sareg0 What do you think is a good fix here --- disabling this feature entirely (creating a group when not logged in), or allowing folks to create a group without an associated user?

**Comment by lislis** [comment]
@vsmart that is a bug. The functionality of creating a group should not be available to not-logged in users, so option 1.

Main reason is that the user who creates a group becomes the group admin. Creating a group without admin would make it a zombie group that can't be edited.

Theoretically option 3 would be a nice idea, but designing a nice UX flow for that is probs more work than option 1.

**Comment by vsmart** [comment]
This was closed in https://github.com/rubycorns/rorganize.it/pull/626/files
