### ISSUE TITLE
Phantom link in alphabetical people overview

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#629]
There is a link in the alphabetical list that links to .. nothing! (`#`)
Should be investigated

This is how the phantom link looks like when hovered

![screenshot-2018-4-17 rorganize it find a rails girls study group](https://user-images.githubusercontent.com/1006478/38890605-2f2466f6-4282-11e8-8985-a3697ad263a1.png)

**Comment by vsmart** [comment]
The phantom link is there and it links to `https://rorganize.it/people#%20`.  The `%20` is a url-encoded `<space>`. There is one user whose username starts with a space (you can see them when you click on the phantom link), therefore the space is displayed in the people overview as "first character". 

To fix: 

1. Fix up this user in the database. My assumption is that the link will then disappear, this will have to be validated. 
2. Improve input validation in the user form to avoid this in the future.

**Comment by vsmart** [comment]
Phantom link is fixed - user was updated in the database!! cc @sareg0 

<img width="648" alt="screen shot 2018-08-14 at 19 44 36" src="https://user-images.githubusercontent.com/2796920/44108389-88421bea-9ffa-11e8-9e46-a1c1e3b376b6.png">

## Pizza time 

![pizza time](https://media.giphy.com/media/WarzOpHYADJew/giphy.gif)
