### ISSUE TITLE
500 error when trying to access nonexistent blog page

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#645]
```[RORGANIZE ERROR](2 times) posts#index (RangeError) "invalid page: -4097"```

There is another (automated) attempt to hack our site via this

**Comment by PragTob** [comment]
:scream: 

you sure it's hacking and not ust crawling?

**Comment by lislis** [comment]
hmm, yah. The exact get request url was
``` https://rorganize.it/posts?page=-4097%20UNION%20ALL%20SELECT%20CONCAT%280x7178707671%2C0x5455657865556e4957557a6e4141454a6f4e6b765558515359556d465872726d447442495645694e%2C0x71706b7671%29%23```

**Comment by PragTob** [comment]
oh yeah that's definitely trying SQL injection. Good catch.

**Comment by sareg0** [comment]
whee!! I wanna do eeet! #security

**Comment by sareg0** [comment]
We have merged a PR to solve this, so closing the issue up. Thanks for reporting @lislis
