### ISSUE TITLE
upgrade to rails 5.2

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#646]

**Comment by sareg0** [comment]
I am volunteering myself #productivicorn

**Comment by lislis** [comment]
coming in #680

**Comment by lislis** [comment]
needs to be fixed, too #619

**Comment by sareg0** [comment]
@lislis does #619 need to be solved before your PR can be ready?

**Comment by lislis** [comment]
Yes indeed!

**Comment by vsmart** [comment]
We're running on rails 5.2.3 now.
