### ISSUE TITLE
[feature] Group admin should have rights to delete their group

### ISSUE THREAD

**Issue by vsmart** [rubycorns/rorganize.it#650]
## To reproduce

* Created a new group
* You'll be group admin
* Could not delete the group (or I couldn't find the button?)

**Comment by Seunadex** [comment]
@vsmart  [PR-670](https://github.com/rubycorns/rorganize.it/pull/670)

**Comment by lislis** [comment]
Thanks @Seunadex  for building this!
Done and closing!
