### ISSUE TITLE
[feature] My groups tab 

### ISSUE THREAD

**Issue by vsmart** [rubycorns/rorganize.it#664]
I would like a `My Groups` tab in the groups view. 
For a quick access to my groups! 

<img width="1059" alt="screen shot 2018-11-20 at 21 51 24" src="https://user-images.githubusercontent.com/2796920/48802200-c4b01800-ed0e-11e8-97c5-71d9ecd29d92.png">

✨ Thanks corns! ✨

**Comment by Seunadex** [comment]
I will like to take a stab at this.

**Comment by lislis** [comment]
Closed by #666
