### ISSUE TITLE
My groups tabs should only show when user is logged in

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#667]
I just deployed the `My Groups` feature and noticed the tab also shows up when I'm not logged in.
Clicking it results in a 503, which is correct but not so nice to look at.

We should only show the tab when the user is logged in.

**Comment by lislis** [comment]
@Seunadex since you worked on the original feature, would you like to work on this as well?

**Comment by Seunadex** [comment]
@lislis Yes i will

**Comment by Seunadex** [comment]
it's ready [668](https://github.com/rubycorns/rorganize.it/pull/668)  @lislis

**Comment by lislis** [comment]
Thank you very much! It's online already!
