### ISSUE TITLE
Remove accidental test group

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#677]
I think one of us was testing in production so I want to check it's okay to maybe delete this group: https://rorganize.it/groups/jfkjdl

**Comment by PragTob** [comment]
Might have been just anyone testing stuff out. I'm pretty confident we can delete it. Thanks for the observation Sara!

**Comment by lislis** [comment]
I deleted the group!
Good job everyone!
![team high 5](https://media.giphy.com/media/7L9FYvnh467YI/giphy.gif)

**Comment by lislis** [comment]
@Seunadex you were marked as the coach of that group. I hope that was ok!
