### ISSUE TITLE
Transfer github app ownershipt to rubycorns org

### ISSUE THREAD

**Issue by vsmart** [rubycorns/rorganize.it#682]
Our 2 github applications are owned by individuals, @berlintam and @FrauBienenstich:

<img width="461" alt="Screenshot 2019-08-30 at 16 24 42" src="https://user-images.githubusercontent.com/2796920/64055697-fe863880-cb42-11e9-8c49-a083bb9c03e5.png">

We should get that ownership transfered to the org. 

@berlintam @FrauBienenstich Can you run this out and comment back? It's a button in the application settings: Settings > Developer Settings > App > Transfer github application

## Todo

* [x] Transfer `rorganize app production`
* [x] Transfer `rorganize.it`

**Comment by berlintam** [comment]
@lislis and I handled this today :tada:
