### ISSUE TITLE
Replace `devise_error_messages!` with modified partials

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#684]
When running tests, we get a deprecation warning from Devis.

```
DEPRECATION WARNING: [Devise] `DeviseHelper.devise_error_messages!`
is deprecated and it will be removed in the next major version.
To customize the errors styles please run `rails g devise:views` and modify the
`devise/shared/error_messages` partial.
```

Ahead of this being fully deprecated, let's do what the warning message tell us and add some partials with shared error messages. 

You can reproduce this deprecation warning by running `bundle exec rspec`. You'll see a whole bunch

**Comment by vsmart** [comment]
closed in #690
