### ISSUE TITLE
Renew Security Certificate

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#694]
Looks like our Security cert is out of date. 

I'm not exactly sure how to update it, but I'm happy to help take care of it with someone who does know. I'm presuming we might need to log into our hosting provider and renew it? Please fill us in on the issue.

**Comment by lislis** [comment]
so I'm not exactly sure what happened. 

# What happened

We have a cron job that was supposed to run monthly to update the cert, which is only valid for 90 days.
For some reason it wasn't renewd and then cert expired and the error caused our ping script to execute every 5 minutes (as it should). We're only pinging http**s**://rorganize which, with the expried cert, was not reachable.

I've seen in my inbox that we did get a notification from Uberspace that the cert expired last night. at around 23:24 when I wasn't checking mails anymore ...
```
Dein TLS-Zertifikat für rorganize.it ist ausgelaufen und wir haben
es daher aus unserer Konfiguration entfernt. Das bedeutet nicht automatisch,
dass rorganize.it nicht mehr über eines deiner anderen Zertifikate 
abgedeckt ist, über den Befehl ...

[ror@schedar ~]$ uberspace-list-certificates
We don't have any certificates.

... kannst du dir anschauen, welche Zertifikate für deinen Account eingetragen
sind und für welche Domains sie gelten.

Wie du neue Zertifikate eintragen kannst, haben wir unter ...

https://wiki.uberspace.de/webserver:https#nutzung_eigener_tls-zertifikate

... beschrieben.
```

# Fixing it

Clicking the link in the mail, there is new documentation around letsencrypt certs.
Previously we had to write our own script, now Uberspace is offering one. 
Also they recommend running the renew-cronjob daily, so I've changed that in the crontab (`crontab -e` and ran the script once, manually.

So, we're up and this should not happen again :crossed_fingers:
